//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fumigate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Fumigate_LiveEntities1 : DbContext
    {
        public Fumigate_LiveEntities1()
            : base("name=Fumigate_LiveEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketVersion> TicketVersions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserPermissionsLink> UserPermissionsLinks { get; set; }
        public virtual DbSet<TicketGrid> TicketGrids { get; set; }
    }
}
