//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fumigate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketVersions = new HashSet<TicketVersion>();
        }
    
        public int TicketId { get; set; }
        public string TicketName { get; set; }
        public int Author { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Title { get; set; }
        public int Priority { get; set; }
    
        public virtual Priority Priority1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketVersion> TicketVersions { get; set; }
    }
}
