//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fumigate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketVersion
    {
        public int ID { get; set; }
        public int Version { get; set; }
        public int TicketId { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int Status { get; set; }
        public int AssignedTo { get; set; }
        public string Comment { get; set; }
    
        public virtual Status Status1 { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
        public virtual User User3 { get; set; }
    }
}
